/**
 * Agent 8 — Assembler
 * Merges frontend files + backend files into one projectFiles map.
 * Also injects React Native code into files if present.
 * No AI call needed — pure JS merge operation.
 */

/**
 * @param {string}                fixedPreview  — fixed CDN preview HTML
 * @param {Record<string,string>} frontendFiles — from Agent 3
 * @param {Record<string,string>} backendFiles  — from Agent 5
 * @param {string}                [nativeCode]  — from Agent 4 (optional)
 * @returns {{ preview: string, projectFiles: Record<string,string> }}
 */
export async function runAssembler(
  fixedPreview,
  frontendFiles = {},
  backendFiles  = {},
  nativeCode    = "",
) {
  // Merge all project files
  const projectFiles = {
    ...frontendFiles,
    ...backendFiles,
  };

  // Inject React Native code as a file if it exists
  if (nativeCode) {
    projectFiles["mobile/App.js"] = nativeCode;
    projectFiles["mobile/README.md"] =
      "# React Native App (Expo)\n\nThis mobile app was generated alongside the web project.\n\n```bash\nnpm install\nnpx expo start\n```\n";
  }

  // Add a root-level README if not already present
  if (!projectFiles["README.md"]) {
    const name = Object.keys(backendFiles).length > 0 ? "MERN Stack" : "React";
    projectFiles["README.md"] = generateReadme(name, projectFiles);
  }

  return { preview: fixedPreview, projectFiles };
}

function generateReadme(stackName, files) {
  const hasBackend = Object.keys(files).some(k => k.startsWith("server/"));
  const hasMobile  = Object.keys(files).some(k => k.startsWith("mobile/"));

  return `# ${stackName} Project

Generated by **EasyWay AI Website Builder**.

## Project Structure

\`\`\`
${Object.keys(files).slice(0, 20).join("\n")}
\`\`\`

## Getting Started

### Client (React + Vite)
\`\`\`bash
cd client
npm install
npm run dev
\`\`\`
${hasBackend ? `
### Server (Node.js + Express + MongoDB)
\`\`\`bash
cd server
npm install
cp .env.example .env
# Edit .env with your MongoDB URI
npm run dev
\`\`\`` : ""}
${hasMobile ? `
### Mobile (Expo React Native)
\`\`\`bash
cd mobile
npm install
npx expo start
\`\`\`` : ""}

## Tech Stack
- **Frontend**: React 18, Vite, Three.js, React Router
- **Backend**: Node.js, Express, MongoDB, Mongoose
- **Styling**: CSS Custom Properties (monochrome by default)
`;
}
